# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Code Coverage

permissions:
  contents: write
  pull-requests: write
  checks: write

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
    
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
        
    - name: Install dependencies for projects
      run: yarn install
        
    - name: Test and Code Coverage
      run: yarn test:cov
      
    - uses: ArtiomTr/jest-coverage-report-action@v2
      with:
          custom-title: Coverage Report for API
          skip-step: all
          coverage-file: ./coverage/coverage-final.json
