name: Code Coverage

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  coverage:
    permissions:
        contents: write
        pull-requests: write
        checks: write

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
        - uses: actions/checkout@v4
        - name: Use Node.js ${{ matrix.node-version }}
    
        - uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'yarn'
        
        - name: Install dependencies for projects
          run: yarn install
        
        - name: Test and Code Coverage
          run: yarn test:cov
      
        - uses: jwalton/gh-find-current-pr@v1
          id: findPr

        - uses: ArtiomTr/jest-coverage-report-action@v2
          with:
            prnumber: ${{ steps.findPr.outputs.number }}
            custom-title: Coverage Report for API
            skip-step: all
            coverage-file: ./coverage/coverage-final.json
            output: comment, report-markdown
